### ISSUE TITLE
Coradova5 can not build

### ISSUE THREAD

**Issue by ctl1690** [cranberrygame/cordova-plugin-ad-admob#1]
cordova 5 + cordova-plugin-crosswalk-webview can not build.

![2](https://cloud.githubusercontent.com/assets/2221790/7719004/4733b314-feec-11e4-8d5c-ae5e80b705bc.png)

**Comment by cranberrygame** [comment]
@ctl1690 
Fixed the problem.
You can now use this plugin in cordova5.
Thanks

**Comment by ctl1690** [comment]
Thanks a lot.
