### ISSUE TITLE
Cocoon.io compiling problem

### ISSUE THREAD

**Issue by dreamiolab** [cranberrygame/cordova-plugin-ad-admob#12]
Hi,

when I compiling my application with your plugin cordova-plugin-ad-admob, compilation fails. Can you please verify the functionality of the plugin with cocoon.io? Thank you.

Here is a compilation error message:

`Removed LAUNCHER flag
ANDROID_HOME=opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
null
org.xwalk:xwalk_core_library:18+
Not writing assets/xwalk-command-line since file already exists.
:preBuild UP-TO-DATE
:preArmv7ReleaseBuild UP-TO-DATE
:checkArmv7ReleaseManifest
:preX86ReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:cordova-plugin-ad-unityads-sdk:android:preBuild UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:preReleaseBuild UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:compileReleaseNdk UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:compileLint
:cordova-plugin-ad-unityads-sdk:android:copyReleaseLint UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:mergeReleaseProguardFiles
:cordova-plugin-ad-unityads-sdk:android:packageReleaseRenderscript UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:checkReleaseManifest
:cordova-plugin-ad-unityads-sdk:android:preReleaseUnitTestBuild UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
:cordova-plugin-ad-unityads-sdk:android:prepareReleaseDependencies
:cordova-plugin-ad-unityads-sdk:android:compileReleaseRenderscript
:cordova-plugin-ad-unityads-sdk:android:generateReleaseResValues
:cordova-plugin-ad-unityads-sdk:android:generateReleaseResources
:cordova-plugin-ad-unityads-sdk:android:packageReleaseResources
:cordova-plugin-ad-unityads-sdk:android:compileReleaseAidl
:cordova-plugin-ad-unityads-sdk:android:generateReleaseBuildConfig
:cordova-plugin-ad-unityads-sdk:android:generateReleaseAssets UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:mergeReleaseAssets
:cordova-plugin-ad-unityads-sdk:android:mergeReleaseResources
:cordova-plugin-ad-unityads-sdk:android:processReleaseManifest
:cordova-plugin-ad-unityads-sdk:android:processReleaseResources
:cordova-plugin-ad-unityads-sdk:android:generateReleaseSources
:cordova-plugin-ad-unityads-sdk:android:compileReleaseJavaWithJavac
:cordova-plugin-ad-unityads-sdk:android:processReleaseJavaRes UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:transformResourcesWithMergeJavaResForRelease
:cordova-plugin-ad-unityads-sdk:android:transformClassesAndResourcesWithSyncLibJarsForRelease
:cordova-plugin-ad-unityads-sdk:android:mergeReleaseJniLibFolders
:cordova-plugin-ad-unityads-sdk:android:transformNative_libsWithMergeJniLibsForRelease
:cordova-plugin-ad-unityads-sdk:android:transformNative_libsWithSyncJniLibsForRelease
:cordova-plugin-ad-unityads-sdk:android:bundleRelease
:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
:prepareAndroidCordovaPluginAdUnityadsSdkAndroidUnspecifiedReleaseLibrary
:preArmv7DebugBuild UP-TO-DATE
:preX86DebugBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:cordova-plugin-ad-unityads-sdk:android:preDebugBuild UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:compileDebugNdk UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:copyDebugLint UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:mergeDebugProguardFiles
:cordova-plugin-ad-unityads-sdk:android:packageDebugRenderscript UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:checkDebugManifest
:cordova-plugin-ad-unityads-sdk:android:preDebugAndroidTestBuild UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:preDebugUnitTestBuild UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:cordova-plugin-ad-unityads-sdk:android:prepareDebugDependencies
:cordova-plugin-ad-unityads-sdk:android:compileDebugRenderscript
:cordova-plugin-ad-unityads-sdk:android:generateDebugResValues
:cordova-plugin-ad-unityads-sdk:android:generateDebugResources
:cordova-plugin-ad-unityads-sdk:android:packageDebugResources
:cordova-plugin-ad-unityads-sdk:android:compileDebugAidl
:cordova-plugin-ad-unityads-sdk:android:generateDebugBuildConfig
:cordova-plugin-ad-unityads-sdk:android:generateDebugAssets UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:mergeDebugAssets
:cordova-plugin-ad-unityads-sdk:android:mergeDebugResources
:cordova-plugin-ad-unityads-sdk:android:processDebugManifest
:cordova-plugin-ad-unityads-sdk:android:processDebugResources
:cordova-plugin-ad-unityads-sdk:android:generateDebugSources
:cordova-plugin-ad-unityads-sdk:android:compileDebugJavaWithJavac
:cordova-plugin-ad-unityads-sdk:android:processDebugJavaRes UP-TO-DATE
:cordova-plugin-ad-unityads-sdk:android:transformResourcesWithMergeJavaResForDebug
:cordova-plugin-ad-unityads-sdk:android:transformClassesAndResourcesWithSyncLibJarsForDebug
:cordova-plugin-ad-unityads-sdk:android:mergeDebugJniLibFolders
:cordova-plugin-ad-unityads-sdk:android:transformNative_libsWithMergeJniLibsForDebug
:cordova-plugin-ad-unityads-sdk:android:transformNative_libsWithSyncJniLibsForDebug
:cordova-plugin-ad-unityads-sdk:android:bundleDebug
:prepareCanvasplusReleaseLibrary
:prepareComAndroidSupportAppcompatV72311Library
:prepareComAndroidSupportSupportV42400Beta1Library
:prepareComGoogleAndroidGmsPlayServicesAds830Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics902Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl902Library
:prepareComGoogleAndroidGmsPlayServicesBase902Library
:prepareComGoogleAndroidGmsPlayServicesBasement902Library
:prepareComGoogleAndroidGmsPlayServicesDrive830Library
:prepareComGoogleAndroidGmsPlayServicesGames830Library
:prepareComGoogleAndroidGmsPlayServicesPlus830Library
:prepareComGoogleAndroidGmsPlayServicesTasks902Library
:prepareComGoogleFirebaseFirebaseCommon902Library
:prepareComSegmentAnalyticsAndroidAnalytics414Library
:prepareDevapplibReleaseLibrary
:prepareOrgXwalkXwalk_core_library184847713Library
:prepareWebviewplusReleaseLibrary
:prepareArmv7ReleaseDependencies
:compileArmv7ReleaseAidl
:compileArmv7ReleaseRenderscript
:generateArmv7ReleaseBuildConfig
:generateArmv7ReleaseAssets UP-TO-DATE
:mergeArmv7ReleaseAssets
:generateArmv7ReleaseResValues
:generateArmv7ReleaseResources
:mergeArmv7ReleaseResources
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-mdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/drawable/detail_default.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xhdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xhdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-mdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-hdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-hdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xxhdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xxhdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:processArmv7ReleaseManifest
:processArmv7ReleaseResources
:generateArmv7ReleaseSources
:compileArmv7ReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: cordova/platforms/android/src/com/ludei/injector/android/InjectorPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:compileArmv7ReleaseNdk UP-TO-DATE
:compileArmv7ReleaseSources
:lintVitalArmv7ReleaseError processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/UnityAds.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/UnityAdsDeviceLog.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/UnityAdsUtils.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/cache/UnityAdsCacheThread.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/data/UnityAdsAdvertisingId$GoogleAdvertisingInfo$GoogleAdvertisingInfoBinder.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/data/UnityAdsDevice.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/unity3d/UnityAdsUnityWrapper.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/video/UnityAdsVideoPlayView$VideoStateChecker.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/view/UnityAdsFullscreenActivity.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/view/UnityAdsMainView$2.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/webapp/UnityAdsWebData.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/webapp/UnityAdsWebView.class: broken class file?
Error processing cordova/platforms/android/build/intermediates/exploded-aar/android.cordova-plugin-ad-unityads-sdk/android/unspecified/release/jars/libs/unity-ads.jar:com/unity3d/ads/android/zone/UnityAdsZone.class: broken class file?

:transformClassesWithDexForArmv7Release
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzr;
at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
at com.android.dx.command.dexer.Main.run(Main.java:277)
at com.android.dx.command.dexer.Main.main(Main.java:245)
at com.android.dx.command.Main.main(Main.java:106)

FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Release'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 11.849 secs
ERROR building one of the platforms: Error code 1 for command: cordova/platforms/android/gradlew with args: cdvBuildRelease,-b,cordova/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
You may not have the required environment or OS to build this project
Error: Error code 1 for command: cordova/platforms/android/gradlew with args: cdvBuildRelease,-b,cordova/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true`

**Comment by cranberrygame** [comment]
@dreamiolab 
Fixed this issue.
Thanks
Sang Ki Kwon
