### ISSUE TITLE
Build Error at Intel XDK

### ISSUE THREAD

**Issue by AndreasReitberger** [cranberrygame/cordova-plugin-ad-admob#2]
Hello,

I tried this plugin and included it in Intel XDK. But then the build crashes without any error message.
If I remove the plugin it works.

Any ideas?

Thank you!

**Comment by JoeSchr** [comment]
The "older" plugin still works at my build: com.cranberrygame.phonegap.plugin.ad.admob

**Comment by AndreasReitberger** [comment]
@JoeSchr Yes it also works on my end, but not the new cordova plugin. Does it work on your end?

**Comment by JoeSchr** [comment]
didn't try yet. never change a running system... ;)

**Comment by AndreasReitberger** [comment]
Well it doesn't work on my end, see here: https://www.scirra.com/forum/admobads-how-do-i-show-banner-with-overlap-set-to-no_p958951?#p958951

**Comment by JoeSchr** [comment]
sry, can't help with that, I'm using it on the cordova plattform via XDK. maybe try the original plugin com.admob.plugin from google themself?

**Comment by AndreasReitberger** [comment]
I did, but the issue remains the same. Maybe it's just a bug from C2.

**Comment by JoeSchr** [comment]
I just got an crash while testing com.admob.plugin, I posted an Issue comment there: https://github.com/admob-google/admob-cordova/issues/7

**Comment by cranberrygame** [comment]
@AndreasReitberger
@JoeSchr

Build test but no build error.
Thanks

**Comment by slaczky** [comment]
I have the same problem.
Error: "admob" failed to install
building for wp8

**Comment by cranberrygame** [comment]
@slaczky 
Hi
XDK does not support wp8

**Comment by slaczky** [comment]
Sorry I forgot to say that it is wp8.1
XDK wp8.1 support: https://software.intel.com/de-de/forums/topic/563699
I can run my game on wp8.1 device, I made a successfull build with old admob plugin, but ads are not working. Your admob plugins does not support wp8.1?

**Comment by creakosta** [comment]
I have the same question. This is admob plugins support wp8.1?

**Comment by creakosta** [comment]
I create game on Construct 2 and build on XDK v2548 cordova SLI 5.1.1. for android crosswalk and wp8.1 with this plugin,  ads show on android, but not show on wp8.1. I tried many cardova admob plug-ins, but no one does not work with wp8.1. I would be grateful for any help.
