### ISSUE TITLE
[Intel XDK] Build error for iOS while Android is working fine 

### ISSUE THREAD

**Issue by AndreasReitberger** [cranberrygame/cordova-plugin-ad-admob#20]
Hi,

I keep getting build errors on iOS while the Android build is working fine for me. I'm using Intel XDK 3759. Here is the build log.

> CompileC build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobPlugin.o Dawn\ of\ Dan/Plugins/cordova-plugin-ad-admob/AdMobPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
>     cd .../cordova_project/platforms/ios
>     export LANG=en_US.US-ASCII
>     export PATH="/Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../usr/bin:/Applications/Xcode.app/Contents.../usr/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools:/platform-tools"
>     /Applications/Xcode.app/Contents.../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/fz/sblzptkd1q3fnbszfvchxnfr0000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-generated-files.hmap -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-own-target-headers.hmap -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-all-target-headers.hmap -iquote .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-project-headers.hmap -I.../cordova_project/platforms/ios/build/device/include -I.../cordova_project/platforms/ios/build/device/usr/local/lib/include -I.../cordova_project/platforms/ios/build/UninstalledProducts/include -I.../cordova_project/platforms/ios/build/UninstalledProducts/iphoneos/include -I.../cordova_project/platforms/ios/build/device -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/DerivedSources/armv7 -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/DerivedSources -F.../cordova_project/platforms/ios/build/device -FDawn\ of\ Dan/Plugins/cordova-plugin-ad-admob-sdk -include .../cordova_project/platforms/ios/build/sharedpch/Dawn\ of\ Dan-Prefix-gfdatmrmbovqadfkztugmlxmorto/Dawn\ of\ Dan-Prefix.pch -MMD -MT dependencies -MF .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobPlugin.d --serialize-diagnostics .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobPlugin.dia -c .../cordova_project/platforms/ios/Dawn\ of\ Dan/Plugins/cordova-plugin-ad-admob/AdMobPlugin.m -o .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobPlugin.o
> In file included from .../cordova_project/platforms/ios/Dawn of Dan/Plugins/cordova-plugin-ad-admob/AdMobPlugin.m:5:
> .../cordova_project/platforms/ios/Dawn of Dan/Plugins/cordova-plugin-ad-admob/AdMobPlugin.h:9:9: fatal error: 'GoogleMobileAds/GADAdSize.h' file not found
> #import <GoogleMobileAds/GADAdSize.h>
>         ^
> 1 error generated.
> 
> CompileC build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobOverlap.o Dawn\ of\ Dan/Plugins/cordova-plugin-ad-admob/AdMobOverlap.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
>     cd .../cordova_project/platforms/ios
>     export LANG=en_US.US-ASCII
>     export PATH="/Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../usr/bin:/Applications/Xcode.app/Contents.../usr/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools:/platform-tools"
>     /Applications/Xcode.app/Contents.../Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/fz/sblzptkd1q3fnbszfvchxnfr0000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents.../Platforms/iPhoneOS.platform.../SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-generated-files.hmap -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-own-target-headers.hmap -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-all-target-headers.hmap -iquote .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Dawn\ of\ Dan-project-headers.hmap -I.../cordova_project/platforms/ios/build/device/include -I.../cordova_project/platforms/ios/build/device/usr/local/lib/include -I.../cordova_project/platforms/ios/build/UninstalledProducts/include -I.../cordova_project/platforms/ios/build/UninstalledProducts/iphoneos/include -I.../cordova_project/platforms/ios/build/device -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/DerivedSources/armv7 -I.../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/DerivedSources -F.../cordova_project/platforms/ios/build/device -FDawn\ of\ Dan/Plugins/cordova-plugin-ad-admob-sdk -include .../cordova_project/platforms/ios/build/sharedpch/Dawn\ of\ Dan-Prefix-gfdatmrmbovqadfkztugmlxmorto/Dawn\ of\ Dan-Prefix.pch -MMD -MT dependencies -MF .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobOverlap.d --serialize-diagnostics .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobOverlap.dia -c .../cordova_project/platforms/ios/Dawn\ of\ Dan/Plugins/cordova-plugin-ad-admob/AdMobOverlap.m -o .../cordova_project/platforms/ios/build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobOverlap.o
> In file included from .../cordova_project/platforms/ios/Dawn of Dan/Plugins/cordova-plugin-ad-admob/AdMobOverlap.m:5:
> In file included from .../cordova_project/platforms/ios/Dawn of Dan/Plugins/cordova-plugin-ad-admob/AdMobOverlap.h:5:
> .../cordova_project/platforms/ios/Dawn of Dan/Plugins/cordova-plugin-ad-admob/AdMobPlugin.h:9:9: fatal error: 'GoogleMobileAds/GADAdSize.h' file not found
> #import <GoogleMobileAds/GADAdSize.h>
>         ^
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC build/Dawn\ of\ Dan.build/Release-iphoneos/Dawn\ of\ Dan.build/Objects-normal/armv7/AdMobPlugin.o Dawn\ of\ Dan/Plugins/cordova-plugin-ad-admob/AdMobPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> Error: Error code 65 for command: xcodebuild with args: -xcconfig,.../cordova_project/platforms/ios/cordova/build-release.xcconfig,-project,Dawn of Dan.xcodeproj,ARCHS=armv7 arm64,-target,Dawn of Dan,-configuration,Release,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=.../cordova_project/platforms/ios/build/device,SHARED_PRECOMPS_DIR=.../cordova_project/platforms/ios/build/sharedpch

**Comment by carsonlws** [comment]
I am having the same issue with Intelxdk 3759 when build for IOS.
Please advice.

**Comment by anisc** [comment]
@AndreasReitberger @carsonlws @cranberrygame any solution ?
