### ISSUE TITLE
auto start

### ISSUE THREAD

**Issue by aurlev** [cranberrygame/cordova-plugin-ad-admob#4]
hi. it is work.  i would like it the admob run auto with out the on click.so it will start when the user use the app. what is the right thing to do? (i'm new on javascript)
thanks.

**Comment by cranberrygame** [comment]
Hi, @aurlev 

Do like this:

<html>
<head>
	<script type="text/javascript" src="cordova.js"></script>
</head>
<body>

<script>
var bannerAdUnit = "ca-app-pub-4906074177432504/9172302471";
var interstitialAdUnit = "ca-app-pub-4906074177432504/1649035673";
var isOverlap = true; //true: overlap, false: split
var isTest = true;

document.addEventListener("deviceready", function(){
	window.admob.setUp(bannerAdUnit, interstitialAdUnit, isOverlap, isTest);
	
	window.admob.showBannerAd('top-center', 'SMART_BANNER');
	
}, false);
	
</script>

...

</body>
</html>

**Comment by aurlev** [comment]
you are awesome. thank you.
i was very close almost doen the right thing but with little mistakes. 

you are Certainly GREAT   !

**Comment by cranberrygame** [comment]
@aurlev 

Thanks
