### ISSUE TITLE
Can not build on Intel XDK with npm version 1.0.107

### ISSUE THREAD

**Issue by mediadi** [cranberrygame/cordova-plugin-ad-admob#9]
fatal error: 'GoogleMobileAds/GADAdSize.h' file not found
#import <GoogleMobileAds/GADAdSize.h>

**Comment by cranberrygame** [comment]
@mediadi 

Sorry for late reply.

For ios, use not npm (cordova plugin add cordova-plugin-ad-admob) but github (https://github.com/cranberrygame/cordova-plugin-ad-admob) because of ios symbolic link problem in npm.

Thanks
Sang Ki Kwon
